
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # ðŸ’» L'interface Web pour visualiser les traces
      - "4317:4317"   # ðŸ“¡ Le port OTLP gRPC (pour recevoir les donnÃ©es)
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hr_pulse_backend
    ports:
      - "8000:8000"
    environment:
      # On dit au backend d'envoyer les traces au conteneur Jaeger
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - jaeger
    env_file:
      - .env # Injecte dynamiquement ta chaÃ®ne de connexion Azure SQL
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hr_pulse_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend # S'assure que le backend dÃ©marre avant le frontend
    restart: unless-stopped